### ISSUE TITLE
Issue while using on Android

### ISSUE THREAD

**Issue by mdziczkowski** [ichaoX/ext-webRequest#4]
## Instalation info

**OS**: Android 13
**Addon version**: 4.5

## Issue description with taken steps

While using on Android and want to add a rule then:

- I select the "Global request matching" option (for example: "url")

- I remove the context of the edit field
- The text field closes and the selected by me option is beeing reset to the default "Templates"

## Expected result

The text field remains open after clearing out the content of the text field

**Comment by ichaoX** [comment]
Deleting all content and showing the template options is the expected behavior.

Although it may seem counterintuitive, this is currently the only way to return to the template options.

Additionally, "Global request matching" is a global whitelist; it will continue to test the matching of rules only if it returns true.

**Comment by mdziczkowski** [comment]
I think that it would be better that the "template options" could be selected independantly from the text area content, with should be updated automatically after the option becomes changed.

Additionally, there should exist a possibility to add custom templates.

**Comment by ichaoX** [comment]
> I think that it would be better that the "template options" could be selected independantly from the text area content, with should be updated automatically after the option becomes changed.
> 
> Additionally, there should exist a possibility to add custom templates.

If you do not want to use the default template, you can choose "Other."

Having both the textarea and template options available may cause confusion, and switching templates will replace the user's input.

You can add the current code as a template by clicking the "☆ / Add Template" button on the right side of the textarea.

**Comment by mdziczkowski** [comment]
I think also that users would appreciate it very much if anything would be best as possible documented (that also includes giving examples and references) that would make the usage as simple as possible 😜

**Comment by ichaoX** [comment]
> I think also that users would appreciate it very much if anything would be best as possible documented (that also includes giving examples and references) that would make the usage as simple as possible 😜

See also: #7
