### ISSUE TITLE
how to block POST requests by their Body

### ISSUE THREAD

**Issue by WAZAAAAA0** [ichaoX/ext-webRequest#9]
is it possible to block a specific POST request from being sent if it contains a certain word in it? Hypothetical example:

URL: `https://*.test.example.org/graphql`
Method: `POST`
Request contains this string anywhere in its payload (Body): `ABCthisisatestXYZ`

I read the examples and the template names but couldn't find a way to filter by body specifically. Appreciate any help

**Comment by ichaoX** [comment]
This is possible. Below is a simple example.

Match Request:
```js
let methods = ['POST'];
if (!methods.includes(details.method)) return false;

let regex = /^https:\/\/([^\/]+\.)?example\.org\/graphql/i;
return regex.test(details.url);
```

BeforeRequest:
```js
// https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest#requestbody

if (details.requestBody) {
    try {
        let bodyText = '';
        if (details.requestBody.raw) {
            let decoder = new TextDecoder('utf-8');
            bodyText = details.requestBody.raw.reduce((s, x) => s + decoder.decode(x.bytes, { stream: true }), '') + decoder.decode();
        } else if (details.requestBody.formData) {
            bodyText = JSON.stringify(details.requestBody.formData);
        }
        if (bodyText.includes('ABCthisisatestXYZ')) return { cancel: true };
    } catch (e) {
        console.warn(e, details.requestBody);
    }
}
```

Firefox may have incomplete support for form data that includes files.

https://bugzilla.mozilla.org/show_bug.cgi?id=1268885

**Comment by WAZAAAAA0** [comment]
Amazing. It worked so well you could probably add it to `Examples.md`! Thank you.
